export const FETCH_AUTH_KEY = 'FETCH_AUTH_KEY';
export const SET_AUTH_KEY = 'SET_AUTH_KEY';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';